reference_route_table = [
    {
        "id": "1524976326",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "192.168.3.3/24",
        "prefix": 24,
        "protocol": "C",
        "vrf": "local",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "subnet-0f1a2a447d71c7695",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976326",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "192.168.2.2/24",
        "prefix": 24,
        "protocol": "C",
        "vrf": "local",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "subnet-0f1a2a447d71c7695",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976326",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.123.0/24",
        "prefix": 24,
        "protocol": "C",
        "vrf": "rtb-0939a843a1a6a0b8e",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "subnet-0f1a2a447d71c7695",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976355",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.0.0/16",
        "prefix": 16,
        "protocol": "S",
        "vrf": "rtb-0939a843a1a6a0b8e",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": None,
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": "local",
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976310",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.0.0/24",
        "prefix": 24,
        "protocol": "C",
        "vrf": "rtb-0939a843a1a6a0b8e",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "subnet-0d8a0d39246da46be",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976352",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.32.0.0/16",
        "prefix": 16,
        "protocol": "S",
        "vrf": "rtb-0939a843a1a6a0b8e",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "pcx-0f12f139aab0718b9",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": "VPC vpc-0e20d627d66d8b8ae via VPC Peering pcx-0f12f139aab0718b9",
                "vni": None,
                "vrfLeak": "local",
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976360",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "0.0.0.0/0",
        "prefix": 0,
        "protocol": "S",
        "vrf": "rtb-0939a843a1a6a0b8e",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "igw-05b7cb548386d8f6b",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": "Route via Gateway igw-05b7cb548386d8f6b",
                "vni": None,
                "vrfLeak": "local",
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976346",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.0.0/16",
        "prefix": 16,
        "protocol": "S",
        "vrf": "rtb-0d70e393ae693aeb9",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": None,
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": "local",
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976334",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.123.0/24",
        "prefix": 24,
        "protocol": "C",
        "vrf": "local",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": None,
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": "rtb-0939a843a1a6a0b8e",
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976320",
        "sn": "vpc-034a73438c0064932",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.0.0/24",
        "prefix": 24,
        "protocol": "S",
        "vrf": "local",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "Gi0/0",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": "rtb-0939a843a1a6a0b8e",
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524976861",
        "sn": "igw-05b7cb548386d8f6b",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.0.0/16",
        "prefix": 16,
        "protocol": "S",
        "vrf": "",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "vpc-034a73438c0064932",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": "Route via the attached VPC vpc-034a73438c0064932",
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524965523",
        "sn": "nat-0d76524f9b9ae0579",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "0.0.0.0/0",
        "prefix": 0,
        "protocol": "S",
        "vrf": "",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "eni-01e7ae2a5ec182765",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": "Default route via VPC vpc-034a73438c0064932",
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
    {
        "id": "1524965518",
        "sn": "nat-0d76524f9b9ae0579",
        "hostname": "test-peer-pejsek",
        "siteKey": "1132082471",
        "siteName": "AWS_SITE",
        "network": "10.33.0.0/24",
        "prefix": 24,
        "protocol": "C",
        "vrf": "",
        "nhCount": 1,
        "nhLowestAge": None,
        "nhLowestMetric": None,
        "nexthop": [
            {
                "ad": None,
                "age": None,
                "intName": "eni-01e7ae2a5ec182765",
                "ip": None,
                "labels": None,
                "metric": None,
                "oid": None,
                "vni": None,
                "vrfLeak": None,
                "vtepIp": None,
            }
        ],
    },
]
